### import SQL
--------------
사전작업
- 1) Atlas Cohort 생성 (Target / Case)
- 2) DB에서 Target / Case 병합 Table 생성
-------------
변경사항
- 1) current_date
- 2) outcome_name ; 변경하면서 다시 재실행 
- 3) db 정보 및 dbTableSchema 변경
--------------

In [24]:
# @변경 필요한 변수

current_date = 20220326
# outcome_list=['meloxicam', 'celecoxib', 'valproic_acid, lamotrigine']
outcome_name = 'acetaminophen' 
domains = ['measurement', 'drug', 'procedure', 'condition']

nephrotoxicity = True
hepatotoxicity = False

In [2]:
import os
import pathlib
import sys
sys.path.append("..")

current_dir = pathlib.Path.cwd()
parent_dir = current_dir.parent
output_dir = pathlib.Path('{}/data/{}/importsql_lstm/{}/'.format(parent_dir, current_date, outcome_name))
pathlib.Path.mkdir(output_dir, mode=0o777, parents=True, exist_ok=True)

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import datetime
import re
import os
import pandas as pd
import numpy as np
#!pip install pymssql
import pymssql
from datetime import timedelta

pd.set_option('display.max_colwidth', -1)  #각 컬럼 width 최대로 
pd.set_option('display.max_rows', 50)      # display 50개 까지

C:\Users\suncheolheo\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:12: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  if sys.path[0] == '':

# connection DataBase (해당 DB의 명령문 사용)

### Postgresql (계정유출 주의)

In [ ]:
# import pandas.io.sql as psql
# import psycogp2 as pg
# conn = pg.connect(host='111.1.11.11', dbname='cdm', user='1111', password='1111', port='5432')
# print('connection')

# sql = 'select * from cdm.cdm.person'
# population = psql.read(sql=sql1, con=conn)
# population.to_csv('population.txt', index=False)

### Mssql (계정유출 주의)

In [4]:
import pymssql
#conn= pymssql.connect(server="111.111.111.111", user="user", password="password", port=22, database='db', as_dict=False)
conn= pymssql.connect(server="61.252.54.76", user="Atlas", password="dhlab2021!", port=14333, database='CDM', as_dict=False)
print("connection")

connection

### Table Load from DB

In [ ]:
tnPopulation = 'temp.dbo.person_{}'.format(outcome_name)
tnMeasurement = 'CDM.dbo.measurement'
tnDrug = 'CDM.dbo.drug_exposure'
tnProcedure = 'CDM.dbo.procedure_occurrence'
tnCondition = 'CDM.dbo.condition_occurrence'
tnConcept = 'CDM.dbo.concept'

In [ ]:
# 간독성 Patient 불러오기
sql_query = 'select * from {}'.format(tnPopulation)
population_df = pd.read_sql(sql=sql_query, con=conn)

# 결과확인 
print('success : {}'.format(len(population_df)))

### Table Load from DB (Measurement / drug / procedure / concept)

In [ ]:
# Measurement / drug / procedure / concept 불러오기 
sql_query ="select person_id, measurement_concept_id, measurement_date, value_as_number, range_low, range_high from {} ".format(tnMeasurement) +\
    "where measurement_concept_id!=0 and value_as_number is not null and person_id in (select distinct person_id from {})".format(tnPopulation)
meas_df = pd.read_sql(sql=sql_query, con=conn)

sql_query="select person_id, drug_concept_id, drug_exposure_start_date, quantity from {} ".format(tnDrug) +\
    "where drug_concept_id!=0 and quantity is not null and person_id in (select distinct person_id from {})".format(tnPopulation)
drug_df = pd.read_sql(sql=sql_query, con=conn)

sql_query="select person_id, procedure_concept_id, procedure_date from {} ".format(tnProcedure) +\
    "where procedure_concept_id!=0 and person_id in (select distinct person_id from {} )".format(tnPopulation)
proc_df = pd.read_sql(sql=sql_query, con=conn)

sql_query="select person_id, condition_concept_id, condition_start_date from {} ".format(tnCondition) +\
    "where condition_concept_id!=0 and person_id in (select distinct person_id from {} )".format(tnPopulation)
cond_df = pd.read_sql(sql=sql_query, con=conn)

# 결과확인 
print('success : {}, {}, {}, {}'.format(len(meas_df), len(drug_df), len(proc_df), len(cond_df)))

### Table Load from DB (Concept)

In [ ]:
## concept table 전체 불러오기 
# sql_query="select distinct concept_id, concept_name from {}".format(tnConcept)
# concept_df = pd.read_sql(sql=sql_query, con=conn)

## concept table 일부 불러오기 
sql_query="select distinct concept_id, concept_name from {} ".format(tnConcept) +\
    "where concept_id !=0 and concept_id in (select distinct measurement_concept_id from {})".format(tnMeasurement)
concept_meas_df = pd.read_sql(sql=sql_query, con=conn)
sql_query="select distinct concept_id, concept_name from {} ".format(tnConcept) +\
    "where concept_id !=0 and concept_id in (select distinct drug_concept_id from {})".format(tnDrug)
concept_drug_df = pd.read_sql(sql=sql_query, con=conn)
sql_query="select distinct concept_id, concept_name from {} ".format(tnConcept) +\
    "where concept_id !=0 and concept_id in (select distinct procedure_concept_id from {})".format(tnProcedure)
concept_proc_df = pd.read_sql(sql=sql_query, con=conn)
sql_query="select distinct concept_id, concept_name from {} ".format(tnConcept) +\
    "where concept_id !=0 and concept_id in (select distinct condition_concept_id from {})".format(tnCondition)
concept_cond_df = pd.read_sql(sql=sql_query, con=conn)

print(len(concept_meas_df), len(concept_drug_df), len(concept_proc_df), len(concept_cond_df))
concept_df = pd.concat([concept_meas_df, concept_drug_df, concept_proc_df, concept_cond_df], axis=0)
concept_df

conn.close()

### Save dataset

In [ ]:
population_df.to_csv('{}/population.txt'.format(output_dir),index=False)
meas_df.to_csv('{}/measurement.txt'.format(output_dir),index=False)
drug_df.to_csv('{}/drug.txt'.format(output_dir),index=False)
proc_df.to_csv('{}/procedure.txt'.format(output_dir),index=False)
cond_df.to_csv('{}/condition.txt'.format(output_dir),index=False)
concept_df.to_csv('{}/concept.txt'.format(output_dir),index=False)

### Load dataset

In [141]:
# 데이터 불러오기
population_df=pd.read_csv('{}/population.txt'.format(output_dir))
meas_df=pd.read_csv('{}/measurement.txt'.format(output_dir))
drug_df=pd.read_csv('{}/drug.txt'.format(output_dir))
proc_df=pd.read_csv('{}/procedure.txt'.format(output_dir))
cond_df=pd.read_csv('{}/condition.txt'.format(output_dir))
concept_df=pd.read_csv('{}/concept.txt'.format(output_dir))

In [142]:
# population_df['label'] = (~population_df['first_abnormal_date'].isnull()).astype(int)
population_df.rename(columns={'gender_source_value':'sex'}, inplace=True)
population_df['sex'].replace(['F', 'Female'], 0, inplace=True)
population_df['sex'].replace(['M', 'Male'], 1, inplace=True)

# meas_df = meas_df[["person_id","measurement_concept_id","measurement_date","value_as_number"]]
meas_df = meas_df[["person_id", "measurement_concept_id", "measurement_date", "value_as_number", "range_low", "range_high"]]
drug_df = drug_df[["person_id","drug_concept_id","drug_exposure_start_date","quantity"]]
proc_df = proc_df[["person_id","procedure_concept_id","procedure_date"]]
cond_df = cond_df[["person_id","condition_concept_id","condition_start_date"]]
concept_df = concept_df[["concept_id","concept_name"]]

def drop_duplicates_(domain_df):
    n_prev = len(domain_df)
    domain_df = domain_df.drop_duplicates()
    n_next = len(domain_df)
    print('{}>{}'.format(n_prev, n_next))
    return domain_df

meas_df = drop_duplicates_(meas_df)
drug_df = drop_duplicates_(drug_df)
proc_df = drop_duplicates_(proc_df)
cond_df = drop_duplicates_(cond_df)

### @use common terminology.
meas_df.rename(columns={'measurement_concept_id':'concept_id','measurement_date':'concept_date','value_as_number':'concept_value'}, inplace=True)
drug_df.rename(columns={'drug_concept_id':'concept_id','drug_exposure_start_date':'concept_date','quantity':'concept_value'}, inplace=True)
proc_df.rename(columns={'procedure_concept_id':'concept_id','procedure_date':'concept_date'}, inplace=True)
cond_df.rename(columns={'condition_concept_id':'concept_id','condition_start_date':'concept_date'}, inplace=True)

### population + domain
meas_df = pd.merge(population_df, meas_df, left_on=["person_id"], right_on=["person_id"], how="inner").reset_index(drop=True)
drug_df = pd.merge(population_df, drug_df, left_on=["person_id"], right_on=["person_id"], how="inner").reset_index(drop=True)
proc_df = pd.merge(population_df, proc_df, left_on=["person_id"], right_on=["person_id"], how="inner").reset_index(drop=True)
cond_df = pd.merge(population_df, cond_df, left_on=["person_id"], right_on=["person_id"], how="inner").reset_index(drop=True)

25278996>9894766
3144182>2930061
2167882>455150
1684326>1384609

In [143]:
### Get only used dates
def cohortConditionSetting(domain_df, pre_observation_period, post_observation_peroid):
    from datetime import timedelta
    prev_len = len(domain_df)
    domain_df['cohort_start_date'] = pd.to_datetime(domain_df['cohort_start_date'], format='%Y-%m-%d %H:%M:%S', errors='raise')
    # domain_df['first_abnormal_date'] = pd.to_datetime(domain_df['first_abnormal_date'], format='%Y-%m-%d %H:%M:%S', errors='raise')
    domain_df['concept_date'] = pd.to_datetime(domain_df['concept_date'], format='%Y-%m-%d %H:%M:%S', errors='raise')
    # condition 1) Select patients with first adverse events within 2 months of cohort initiation.
    domain_df = domain_df[(domain_df['cohort_start_date']<=domain_df['concept_date']+timedelta(days=pre_observation_period))]
    # condition 2) Delete data before the cohort start date.
    domain_df = domain_df[(domain_df['concept_date']<=domain_df['cohort_start_date']+timedelta(days=post_observation_peroid))]
    # condition 3) Delete data after first_abnormal_date (Except when there is no first abnormal date.)
    # domain_df = domain_df[~(domain_df['first_abnormal_date']<domain_df['concept_date'])]
    # domain_df = domain_df[~(domain_df['first_abnormal_date']-domain_df['cohort_start_date']>timedelta(days=post_observation_peroid))]
    domain_df = domain_df.reset_index(drop=True)
    curr_len = len(domain_df)
    print('{} > {}'.format(prev_len, curr_len))
    return domain_df    

meas_df = cohortConditionSetting(meas_df, pre_observation_period=60, post_observation_peroid=60)
drug_df = cohortConditionSetting(drug_df, pre_observation_period=60, post_observation_peroid=60)
proc_df = cohortConditionSetting(proc_df, pre_observation_period=60, post_observation_peroid=60)
cond_df = cohortConditionSetting(cond_df, pre_observation_period=60, post_observation_peroid=60)

### population + domain + concept
meas_df = pd.merge(meas_df,concept_df,left_on=["concept_id"],right_on=["concept_id"],how="inner")
drug_df = pd.merge(drug_df,concept_df,left_on=["concept_id"],right_on=["concept_id"],how="inner")
proc_df = pd.merge(proc_df,concept_df,left_on=["concept_id"],right_on=["concept_id"],how="inner")
cond_df = pd.merge(cond_df,concept_df,left_on=["concept_id"],right_on=["concept_id"],how="inner")

9894766 > 2637886
2930061 > 856270
455150 > 114952
1384609 > 215524

In [130]:
### @temp code
meas_df['range_high'] = 34

### hepatotoxicity (간독성)

### setting first abnormal date

In [131]:
if hepatotoxicity :
    _3times = 3
    _2times = 2
    _1_5times = 1.5

    concept_id_AST = 3013721
    concept_id_ALT = 3006926
    concept_id_ALP = 3000963
    concept_id_TBL = 3024128

    # 1) 간독성 
    #    - 1-1) 신촌 Normal Range
    #    - 1-2) 강남 Normal Range
    hepatotoxicity_AST_pre=[['F',concept_id_AST,'>',34],  ['M',concept_id_AST,'>',34]]                    # AST : 13-34
    hepatotoxicity_ALT_pre=[['F',concept_id_ALT,'>',46],  ['M',concept_id_ALT,'>',46]]                    # ALT : 5~46
    hepatotoxicity_ALP_pre=[['F',concept_id_ALP,'>',390], ['M',concept_id_ALP,'>',151]]                   # ALP : male:50-151 female:50-390
    hepatotoxicity_TBL_pre=[['F',concept_id_TBL,'>',1.5], ['M',concept_id_TBL,'>',1.8]]                   # TBL : male:0.2-1.8 female:0.2-1.5

    hepatotoxicity_AST=[['F',concept_id_AST,'>',34*_3times],  ['M',concept_id_AST,'>',34*_3times]]        # AST : 13-34
    hepatotoxicity_ALT=[['F',concept_id_ALT,'>',46*_3times],  ['M',concept_id_ALT,'>',46*_3times]]        # ALT : 5~46
    hepatotoxicity_ALP=[['F',concept_id_ALP,'>',390*_2times], ['M',concept_id_ALP,'>',151*_2times]]       # ALP : male:50-151 female:50-390
    hepatotoxicity_TBL=[['F',concept_id_TBL,'>',1.5*_2times], ['M',concept_id_TBL,'>',1.8*_2times]]       # TBL : male:0.2-1.8 female:0.2-1.5
    #    - 1-3) 건양대 Normal Range

    def extraction_of_past_abnormalities(domain_df, concept_id, value):
        n_prev_data = len(domain_df)
        n_prev_person = len(domain_df.person_id.unique())
        history_query = """(sex==1 and cohort_start_date>=concept_date and concept_id=={} and concept_value>{}) or \
            (sex==0 and cohort_start_date>=concept_date and concept_id=={} and concept_value>{})""" \
            .format(concept_id, value, concept_id, value)
        historynormal_person = domain_df.query(history_query)
        print(history_query)
        n_post_data = len(historynormal_person)
        n_prev_person = len(historynormal_person.person_id.unique())
        # print(historynormal_person)
        print('{} > {}'.format(n_prev_data, n_post_data))
        print('{} > {}'.format(n_prev_person, n_prev_person))
        return historynormal_person

    past_abnormalities_AST = extraction_of_past_abnormalities(meas_df, concept_id_AST, value="range_high")
    past_abnormalities_ALT = extraction_of_past_abnormalities(meas_df, concept_id_ALT, value="range_high")
    past_abnormalities_ALP = extraction_of_past_abnormalities(meas_df, concept_id_ALP, value="range_high")
    past_abnormalities_TBL = extraction_of_past_abnormalities(meas_df, concept_id_TBL, value="range_high")

    past_abnormalities = set(past_abnormalities_AST.person_id.unique()) | \
        set(past_abnormalities_ALT.person_id.unique()) | \
        set(past_abnormalities_ALP.person_id.unique()) | \
        set(past_abnormalities_TBL.person_id.unique())

    print("dropout : n = ", len(past_abnormalities))

    def extraction_of_abnormalities(domain_df, concept_id, value):
        n_prev_data = len(domain_df)
        n_prev_person = len(domain_df.person_id.unique())
        history_query = """(sex==1 and cohort_start_date<concept_date and concept_id=={} and concept_value>=({})) or \
            (sex==0 and cohort_start_date<concept_date and concept_id=={} and concept_value>=({}))""" \
            .format(concept_id, value, concept_id, value)
        historynormal_person = domain_df.query(history_query)
        print(history_query)
        n_post_data = len(historynormal_person)
        n_prev_person = len(historynormal_person.person_id.unique())
        # print(historynormal_person)
        print('{} > {}'.format(n_prev_data, n_post_data))
        print('{} > {}'.format(n_prev_person, n_prev_person))
        return historynormal_person

    abnormalities_AST_range = extraction_of_abnormalities(meas_df, concept_id_AST, value="range_high*3")
    abnormalities_ALT_range = extraction_of_abnormalities(meas_df, concept_id_ALT, value="range_high*3")
    abnormalities_ALP_range = extraction_of_abnormalities(meas_df, concept_id_ALP, value="range_high*2")
    abnormalities_TBL_range = extraction_of_abnormalities(meas_df, concept_id_TBL, value="range_high*2")
    abnormalities_AST_value = extraction_of_abnormalities(meas_df, concept_id_AST, value="200")
    abnormalities_ALT_value = extraction_of_abnormalities(meas_df, concept_id_ALT, value="200")

    abnormalities_df = pd.concat([abnormalities_AST_range, \
            abnormalities_ALT_range, \
            abnormalities_ALP_range, \
            abnormalities_TBL_range, \
            abnormalities_AST_value, \
            abnormalities_ALT_value], axis=0, ignore_index=True)
    
    abnormalities = set(abnormalities_df.person_id.unique())
    print("abnormal : n = ", len(abnormalities))

    # abnormalities_df = meas_df.query("cohort_start_date<concept_date")
    # abnormalities_df = abnormalities_df[abnormalities_df["person_id"].isin(abnormalities)]
    abnormalities_df = abnormalities_df[["person_id", "concept_date"]]
    abnormalities_df = abnormalities_df.sort_values(by=["person_id", "concept_date"], axis=0, ascending=[True, True]).reset_index(drop=True)
    abnormalities_df = abnormalities_df.rename({"concept_date":"first_abnormal_date"}, axis=1)
    abnormalities_df = abnormalities_df.drop_duplicates(subset=['person_id'], keep = 'first')
    print(abnormalities_df)
    # population_df['label'] = (~population_df['first_abnormal_date'].isnull()).astype(int)

(sex==1 and cohort_start_date>=concept_date and concept_id==3013721 and concept_value>range_high) or             (sex==0 and cohort_start_date>=concept_date and concept_id==3013721 and concept_value>range_high)
2604139 > 2889
1261 > 1261
(sex==1 and cohort_start_date>=concept_date and concept_id==3006926 and concept_value>range_high) or             (sex==0 and cohort_start_date>=concept_date and concept_id==3006926 and concept_value>range_high)
2604139 > 0
0 > 0
(sex==1 and cohort_start_date>=concept_date and concept_id==3000963 and concept_value>range_high) or             (sex==0 and cohort_start_date>=concept_date and concept_id==3000963 and concept_value>range_high)
2604139 > 0
0 > 0
(sex==1 and cohort_start_date>=concept_date and concept_id==3024128 and concept_value>range_high) or             (sex==0 and cohort_start_date>=concept_date and concept_id==3024128 and concept_value>range_high)
2604139 > 0
0 > 0
dropout : n =  1261
(sex==1 and cohort_start_date<concept_date and concept_id==3013721 and concept_value>=(range_high*3)) or             (sex==0 and cohort_start_date<concept_date and concept_id==3013721 and concept_value>=(range_high*3))
2604139 > 801
266 > 266
(sex==1 and cohort_start_date<concept_date and concept_id==3006926 and concept_value>=(range_high*3)) or             (sex==0 and cohort_start_date<concept_date and concept_id==3006926 and concept_value>=(range_high*3))
2604139 > 0
0 > 0
(sex==1 and cohort_start_date<concept_date and concept_id==3000963 and concept_value>=(range_high*2)) or             (sex==0 and cohort_start_date<concept_date and concept_id==3000963 and concept_value>=(range_high*2))
2604139 > 0
0 > 0
(sex==1 and cohort_start_date<concept_date and concept_id==3024128 and concept_value>=(range_high*2)) or             (sex==0 and cohort_start_date<concept_date and concept_id==3024128 and concept_value>=(range_high*2))
2604139 > 0
0 > 0
(sex==1 and cohort_start_date<concept_date and concept_id==3013721 and concept_value>=(200)) or             (sex==0 and cohort_start_date<concept_date and concept_id==3013721 and concept_value>=(200))
2604139 > 306
119 > 119
(sex==1 and cohort_start_date<concept_date and concept_id==3006926 and concept_value>=(200)) or             (sex==0 and cohort_start_date<concept_date and concept_id==3006926 and concept_value>=(200))
2604139 > 0
0 > 0
abnormal : n =  266
      person_id first_abnormal_date
0     1540906   2017-04-13
6     1546057   2017-03-22
36    1550640   2018-07-30
37    1574560   2017-11-24
42    1580620   2018-04-29
...       ...          ...
1093  9496834   2019-05-02
1094  9512795   2019-05-16
1098  9573508   2019-08-12
1100  9659545   2019-08-24
1103  9677110   2019-07-28

[266 rows x 2 columns]

### nephrotoxicity(신독성)

In [144]:
### @temp code
meas_df['range_high'] = 1.2

In [145]:
if nephrotoxicity :
    _3times = 3
    _2times = 2
    _1_5times = 1.5

    concept_id_creatinine = 3016723
    # 2) 신독성
    #    - 2-1) 신촌 Normal Range
    #    - 2-2) 강남 Normal Range
    nephrotoxicity_creatinine_pre   =[['F',concept_id_creatinine,'>',0.91],  ['M',concept_id_creatinine,'>',1.19]]                              # creatinine : male:0.32-1.19 female:0.49-0.91
    nephrotoxicity_creatinine       =[['F',concept_id_creatinine,'>',0.91*_1_5times],  ['M',concept_id_creatinine,'>',1.19*_1_5times]]          # creatinine : male:0.32-1.19 female:0.49-0.91
    #    - 2-3) 건양대 Normal Range

    def extraction_of_past_abnormalities(domain_df, concept_id, value):
        n_prev_data = len(domain_df)
        n_prev_person = len(domain_df.person_id.unique())
        history_query = """(sex==1 and cohort_start_date>=concept_date and concept_id=={} and concept_value>{}) or \
            (sex==0 and cohort_start_date>=concept_date and concept_id=={} and concept_value>{})""" \
            .format(concept_id, value, concept_id, value)
        historynormal_person = domain_df.query(history_query)
        print(history_query)
        n_post_data = len(historynormal_person)
        n_prev_person = len(historynormal_person.person_id.unique())
        # print(historynormal_person)
        print('{} > {}'.format(n_prev_data, n_post_data))
        print('{} > {}'.format(n_prev_person, n_prev_person))
        return historynormal_person

    past_abnormalities_creatinine = extraction_of_past_abnormalities(meas_df, concept_id_creatinine, value="range_high")

    past_abnormalities = set(past_abnormalities_creatinine.person_id.unique()) 

    print("dropout : n = ", len(past_abnormalities))

    def extraction_of_abnormalities(domain_df, concept_id, value):
        n_prev_data = len(domain_df)
        n_prev_person = len(domain_df.person_id.unique())
        history_query = """(sex==1 and cohort_start_date<concept_date and concept_id=={} and concept_value>=({})) or \
            (sex==0 and cohort_start_date<concept_date and concept_id=={} and concept_value>=({}))""" \
            .format(concept_id, value, concept_id, value)
        historynormal_person = domain_df.query(history_query)
        print(history_query)
        n_post_data = len(historynormal_person)
        n_prev_person = len(historynormal_person.person_id.unique())
        # print(historynormal_person)
        print('{} > {}'.format(n_prev_data, n_post_data))
        print('{} > {}'.format(n_prev_person, n_prev_person))
        return historynormal_person

    abnormalities_creatinine_value = extraction_of_abnormalities(meas_df, concept_id_creatinine, value="2.4")
    abnormalities = set(abnormalities_creatinine_value.person_id.unique())

    print("abnormal : n = ", len(abnormalities))

    abnormalities_df = abnormalities_creatinine_value[["person_id", "concept_date"]]
    abnormalities_df = abnormalities_df.sort_values(by=["person_id", "concept_date"], axis=0, ascending=[True, True]).reset_index(drop=True)
    abnormalities_df = abnormalities_df.rename({"concept_date":"first_abnormal_date"}, axis=1)
    abnormalities_df = abnormalities_df.drop_duplicates(subset=['person_id'], keep = 'first')
    print(abnormalities_df)

(sex==1 and cohort_start_date>=concept_date and concept_id==3016723 and concept_value>range_high) or             (sex==0 and cohort_start_date>=concept_date and concept_id==3016723 and concept_value>range_high)
2637886 > 0
0 > 0
dropout : n =  0
(sex==1 and cohort_start_date<concept_date and concept_id==3016723 and concept_value>=(2.4)) or             (sex==0 and cohort_start_date<concept_date and concept_id==3016723 and concept_value>=(2.4))
2637886 > 184
34 > 34
abnormal : n =  34
     person_id first_abnormal_date
0    1597328   2016-10-04
25   1683889   2016-09-10
30   1764719   2012-08-03
42   1794542   2019-02-21
44   1918296   2010-06-08
45   1989424   2013-02-01
48   2144717   2015-06-30
53   2407039   2018-03-06
61   2580083   2016-03-27
63   2601799   2017-11-22
108  2761437   2012-03-01
114  2806421   2019-05-15
116  2811138   2014-08-19
117  2811896   2011-09-26
118  2917754   2013-01-02
119  3083340   2018-07-29
123  3169427   2018-10-16
135  3458842   2011-07-28
136  3573195   2010-05-01
142  3812826   2013-01-29
143  3974990   2014-11-19
144  3992042   2017-03-01
145  4054113   2018-06-18
146  4107344   2010-05-21
148  4135896   2012-04-06
152  4155874   2016-06-21
153  4311849   2012-06-21
167  4661384   2018-02-27
173  4727741   2015-05-27
176  4823476   2019-01-18
178  5015040   2018-11-21
179  9059846   2019-01-28
182  9491875   2019-04-29
183  9494628   2019-04-20

### outcome 마다 각 domain dataset 생성

In [147]:
if (len(past_abnormalities) > 0) :
    meas_df = meas_df[~population_df["person_id"].isin(past_abnormalities)]
    drug_df = drug_df[~population_df["person_id"].isin(past_abnormalities)]
    proc_df = proc_df[~population_df["person_id"].isin(past_abnormalities)]
    cond_df = cond_df[~population_df["person_id"].isin(past_abnormalities)]

meas_df = pd.merge(meas_df, abnormalities_df, left_on=["person_id"], right_on=["person_id"], how="left").reset_index(drop=True)
drug_df = pd.merge(drug_df, abnormalities_df, left_on=["person_id"], right_on=["person_id"], how="left").reset_index(drop=True)
proc_df = pd.merge(proc_df, abnormalities_df, left_on=["person_id"], right_on=["person_id"], how="left").reset_index(drop=True)
cond_df = pd.merge(cond_df, abnormalities_df, left_on=["person_id"], right_on=["person_id"], how="left").reset_index(drop=True)

meas_df['label'] = (~meas_df['first_abnormal_date'].isnull()).astype(int)
drug_df['label'] = (~drug_df['first_abnormal_date'].isnull()).astype(int)
proc_df['label'] = (~proc_df['first_abnormal_date'].isnull()).astype(int)
cond_df['label'] = (~cond_df['first_abnormal_date'].isnull()).astype(int)

In [149]:
### Get only used dates
def cohortConditionSetting(domain_df, pre_observation_period, post_observation_peroid):
    from datetime import timedelta
    prev_len = len(domain_df)
    domain_df['cohort_start_date'] = pd.to_datetime(domain_df['cohort_start_date'], format='%Y-%m-%d %H:%M:%S', errors='raise')
    domain_df['first_abnormal_date'] = pd.to_datetime(domain_df['first_abnormal_date'], format='%Y-%m-%d %H:%M:%S', errors='raise')
    domain_df['concept_date'] = pd.to_datetime(domain_df['concept_date'], format='%Y-%m-%d %H:%M:%S', errors='raise')
    # condition 1) Select patients with first adverse events within 2 months of cohort initiation.
    domain_df = domain_df[(domain_df['cohort_start_date']<=domain_df['concept_date']+timedelta(days=pre_observation_period))]
    # condition 2) Delete data before the cohort start date.
    domain_df = domain_df[(domain_df['concept_date']<=domain_df['cohort_start_date']+timedelta(days=post_observation_peroid))]
    # condition 3) Delete data after first_abnormal_date (Except when there is no first abnormal date.)
    domain_df = domain_df[~(domain_df['first_abnormal_date']<domain_df['concept_date'])]
    domain_df = domain_df[~(domain_df['first_abnormal_date']-domain_df['cohort_start_date']>timedelta(days=post_observation_peroid))]
    # domain_df["first_abnormal_date"] = domain_df["first_abnormal_date"].fillna('1970-01-01')
    domain_df = domain_df.reset_index(drop=True)
    curr_len = len(domain_df)
    print('{} > {}'.format(prev_len, curr_len))
    return domain_df    

meas_df = cohortConditionSetting(meas_df, pre_observation_period=60, post_observation_peroid=60)
drug_df = cohortConditionSetting(drug_df, pre_observation_period=60, post_observation_peroid=60)
proc_df = cohortConditionSetting(proc_df, pre_observation_period=60, post_observation_peroid=60)
cond_df = cohortConditionSetting(cond_df, pre_observation_period=60, post_observation_peroid=60)

meas_df['concept_domain'] = 'meas'
drug_df['concept_domain'] = 'drug'
proc_df['concept_domain'] = 'proc'
cond_df['concept_domain'] = 'cond'

meas_df.to_csv('{}/{}_meas_df.txt'.format(output_dir, outcome_name),index=False)
drug_df.to_csv('{}/{}_drug_df.txt'.format(output_dir, outcome_name),index=False)
proc_df.to_csv('{}/{}_proc_df.txt'.format(output_dir, outcome_name),index=False)
cond_df.to_csv('{}/{}_cond_df.txt'.format(output_dir, outcome_name),index=False)

2637886 > 2623626
856270 > 852939
110186 > 109898
215524 > 215345

In [150]:
all_domain_vars_df = pd.concat([meas_df, drug_df, proc_df, cond_df], axis=0, ignore_index=True)
print('label 1 : ', len(all_domain_vars_df[all_domain_vars_df['label']==1].person_id.unique()))
print('label 0 : ', len(all_domain_vars_df[all_domain_vars_df['label']==0].person_id.unique()))

label 1 :  34
label 0 :  6157

In [153]:
drug_df

,person_id,cohort_start_date,sex,age,concept_id,concept_date,concept_value,concept_name,first_abnormal_date,label,concept_domain
0,2577161,2011-08-22,1,51,19106160,2011-08-31,3.0,streptodornase 2500 UNT / streptokinase 10000 UNT Oral Tablet,NaT,0,drug
1,2577161,2011-08-22,1,51,19106160,2011-08-30,3.0,streptodornase 2500 UNT / streptokinase 10000 UNT Oral Tablet,NaT,0,drug
2,2577161,2011-08-22,1,51,19106160,2011-08-29,3.0,streptodornase 2500 UNT / streptokinase 10000 UNT Oral Tablet,NaT,0,drug
3,2577161,2011-08-22,1,51,19106160,2011-10-20,21.0,streptodornase 2500 UNT / streptokinase 10000 UNT Oral Tablet,NaT,0,drug
4,4440259,2014-02-09,0,48,19106160,2014-02-14,3.0,streptodornase 2500 UNT / streptokinase 10000 UNT Oral Tablet,NaT,0,drug
...,...,...,...,...,...,...,...,...,...,...,...
852934,4931794,2010-08-10,0,38,40222495,2010-08-11,30.0,iron succinyl milk protein complex 53.3 MG/ML Oral Solution,NaT,0,drug
852935,4931794,2010-08-10,0,38,40222495,2010-08-10,30.0,iron succinyl milk protein complex 53.3 MG/ML Oral Solution,NaT,0,drug
852936,4931794,2010-08-10,0,38,40222495,2010-08-17,30.0,iron succinyl milk protein complex 53.3 MG/ML Oral Solution,NaT,0,drug
852937,4931794,2010-08-10,0,38,40222495,2010-08-19,30.0,iron succinyl milk protein complex 53.3 MG/ML Oral Solution,NaT,0,drug
852938,4931794,2010-08-10,0,38,40222495,2010-08-19,420.0,iron succinyl milk protein complex 53.3 MG/ML Oral Solution,NaT,0,drug